# Area Labels

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - 'plan/**/*'
      - '*.md'

code:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*'
      - 'app/**/*'

notebooks:
  - changed-files:
    - any-glob-to-any-file:
      - 'notebooks/**/*'

ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'

data:
  - changed-files:
    - any-glob-to-any-file:
      - 'data/**/*'
